# Generated by Django 5.1.6 on 2025-02-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0002_article_year_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'CRUD Blog Web', 'verbose_name_plural': 'Artykuły'},
        ),
    ]
